Repository TEAM-ARK/sprout-backend, pull requests merged in 2021-11, with the labels that each got.

#155 ARK-21 자동로그인
  module-secure/src/main/java/com/ark/inflearn/config/SecurityConfiguration.java
Labels: feature

#152 ARK-16 비밀번호 변경 기능
  module-common/src/test/resources/application-test.yml
  module-member/src/main/java/com/ark/inflearn/entity/Member.java
  module-web/src/main/resources/static/docs/api/open-api-3.0.1.json
Labels: feature

#164 appspec.yml 경로 수정
  appspec.yml
Labels: bug, hotfix

#165 ARK-27 SonarQube 연동
  .github/workflows/sonarqube.yml
  .gitignore
  LICENSE
  README.md
  build.gradle
  module-web/build.gradle
  module-web/src/main/resources/static/docs/api/open-api-3.0.1.json
Labels: documentation, duplicate, feature

#169 :ambulance: open-api-3.0.1.json을 찾지 못하는 문제 해결
  module-web/build.gradle
Labels: hotfix

#171 누락되었던 Redis Configuration 복구
  build.gradle
  deploy.sh
  module-common/src/main/java/com/ark/sprout/redis/RedisConfiguration.java
  module-common/src/main/resources/application.yml
Labels: hotfix

#177 ARK-34 나쁜냄새 제거
  README.md
  module-web/src/main/java/com/ark/sprout/entity/HttpLog.java
  module-web/src/main/java/com/ark/sprout/web/MemberApiController.java
  module-web/src/test/java/com/ark/sprout/web/MemberApiControllerTest.java
Labels: refactor

#180 ARK-35 로그 컨벤션 정리
  module-common/src/main/java/com/ark/sprout/util/LogUtils.java
  module-common/src/test/java/com/ark/sprout/util/LogUtilsTest.java
  module-member/src/main/java/com/ark/sprout/service/MemberService.java
  module-secure/src/main/java/com/ark/sprout/config/SecurityDatabaseInitializer.java
  module-web/src/main/java/com/ark/sprout/entity/HttpLog.java
Labels: feature

#181 ARK-35 로그 컨벤션 정리 (수정)
  build.gradle
  module-common/src/main/java/com/ark/sprout/util/LogUtils.java
  module-common/src/test/java/com/ark/sprout/util/LogUtilsTest.java
  module-member/src/main/java/com/ark/sprout/service/MemberService.java
  module-secure/src/main/java/com/ark/sprout/config/SecurityDatabaseInitializer.java
  module-secure/src/main/java/com/ark/sprout/service/SecurityResourceService.java
  module-web/src/main/java/com/ark/sprout/entity/HttpLog.java
Labels: bug, refactor, feature

#184 ARK-40 게시판 공통 모듈 추출
  build.gradle
  gradle.properties
  module-common/src/main/java/com/ark/sprout/entity/AbstractEntity.java
  module-community-history/build.gradle
  module-community-history/src/main/java/com/ark/sprout/entity/DeleteHistory.java
  module-community-history/src/main/java/com/ark/sprout/entity/EditHistories.java
  module-community-history/src/main/java/com/ark/sprout/entity/EditHistory.java
  module-community-history/src/main/java/com/ark/sprout/repository/DeleteHistoryRepository.java
  module-community-history/src/main/java/com/ark/sprout/repository/EditHistoryRepository.java
  module-community-history/src/main/java/com/ark/sprout/type/ContentType.java
  module-community-history/src/test/java/com/ark/sprout/entity/DeleteHistoryTest.java
  module-community-history/src/test/java/com/ark/sprout/entity/EditHistoriesTest.java
  module-member/src/main/java/com/ark/sprout/entity/Member.java
  settings.gradle
Labels: feature

#187 ARK-41 SameSite=None 임시 설정
  module-secure/src/main/java/com/ark/sprout/config/SecurityConfiguration.java
Labels: feature
