Repository TEAM-ARK/sprout-backend, pull requests merged in 2021-08, with the labels that each got.

#9 User : 엔티티클래스, 레포지토리 생성
  inflearn-back/build.gradle
  inflearn-back/src/main/java/com/ark/inflearnback/domain/category/Category.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/Discount.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/review/Review.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/user/Role.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/user/User.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/user/UserRepository.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/user/UserService.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/video/Video.java
  inflearn-back/src/test/java/com/ark/inflearnback/user/UserTest.java
Labels: enhancement

#15 Lecture와 Review 단방향 관계로 변경
  inflearn-back/src/main/java/com/ark/inflearnback/domain/category/Category.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/course/Course.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/Discount.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/enums/Difficulty.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/enums/Role.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Difficulty.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/review/Review.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/user/User.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/video/Video.java
  inflearn-back/src/test/java/com/ark/inflearnback/user/UserTest.java
Labels: enhancement

#17 feature : auditing 기능
  inflearn-back/src/main/java/com/ark/inflearnback/InflearnBackApplication.java
  inflearn-back/src/main/java/com/ark/inflearnback/common/BaseTimeEntity.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/category/Category.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/course/Course.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/Discount.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/review/Review.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/user/User.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/video/Video.java
  inflearn-back/src/main/resources/application.yml
  inflearn-back/src/test/java/com/ark/inflearnback/auditing/AuditingTest.java
Labels: enhancement

#19 etc : Validation 변경
  inflearn-back/src/main/java/com/ark/inflearnback/domain/category/Category.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/Discount.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/review/Review.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/user/User.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/video/Video.java
Labels: enhancement

#20 feature : 생성자 추가
  inflearn-back/src/main/java/com/ark/inflearnback/domain/category/Category.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/course/Course.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/Discount.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/review/Review.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/user/User.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/video/Video.java
  inflearn-back/src/test/java/com/ark/inflearnback/auditing/AuditingTest.java
  inflearn-back/src/test/java/com/ark/inflearnback/domain/lecture/LectureTest.java
  inflearn-back/src/test/java/com/ark/inflearnback/user/UserTest.java
Labels: enhancement

#22 feature : 엔티티별 Repository 생성
  inflearn-back/src/main/java/com/ark/inflearnback/domain/category/CategoryRepository.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/course/CourseRepository.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/discount/DiscountRepository.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/hashtag/HashtagRepository.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lecture/LectureRepository.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtagRepository.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/review/ReviewRepository.java
  inflearn-back/src/main/java/com/ark/inflearnback/domain/video/VideoRepository.java
  inflearn-back/src/test/java/com/ark/inflearnback/domain/lecture/LectureTest.java
  inflearn-back/src/test/java/com/ark/inflearnback/user/UserTest.java
Labels: enhancement

#26 ⚙ 프로젝트 재구축
  .gitignore
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  inflearn-back/build.gradle
  inflearn-back/settings.gradle
  inflearn-back/src/main/resources/application.yml
  settings.gradle
  src/main/java/com/ark/inflearnback/InflearnBackApplication.java
  src/main/java/com/ark/inflearnback/common/BaseTimeEntity.java
  src/main/java/com/ark/inflearnback/config/logger/P6spyConfig.java
  src/main/java/com/ark/inflearnback/config/logger/P6spyPrettySqlFormatter.java
  src/main/java/com/ark/inflearnback/config/persistence/JpaConfig.java
  src/main/java/com/ark/inflearnback/config/persistence/QuerydslConfig.java
  src/main/java/com/ark/inflearnback/domain/category/Category.java
  src/main/java/com/ark/inflearnback/domain/category/CategoryRepository.java
  src/main/java/com/ark/inflearnback/domain/course/Course.java
  src/main/java/com/ark/inflearnback/domain/course/CourseRepository.java
  src/main/java/com/ark/inflearnback/domain/discount/Discount.java
  src/main/java/com/ark/inflearnback/domain/discount/DiscountRepository.java
  src/main/java/com/ark/inflearnback/domain/enums/Difficulty.java
  src/main/java/com/ark/inflearnback/domain/enums/Role.java
  src/main/java/com/ark/inflearnback/domain/hashtag/Hashtag.java
  src/main/java/com/ark/inflearnback/domain/hashtag/HashtagRepository.java
  src/main/java/com/ark/inflearnback/domain/lecture/Lecture.java
  src/main/java/com/ark/inflearnback/domain/lecture/LectureRepository.java
  src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtag.java
  src/main/java/com/ark/inflearnback/domain/lectureHashtag/LectureHashtagRepository.java
  src/main/java/com/ark/inflearnback/domain/review/Review.java
  src/main/java/com/ark/inflearnback/domain/review/ReviewRepository.java
  src/main/java/com/ark/inflearnback/domain/user/User.java
  src/main/java/com/ark/inflearnback/domain/user/UserRepository.java
  src/main/java/com/ark/inflearnback/domain/user/UserService.java
  src/main/java/com/ark/inflearnback/domain/video/Video.java
  src/main/java/com/ark/inflearnback/domain/video/VideoRepository.java
  src/main/resources/application.yml
  src/test/java/com/ark/inflearnback/InflearnBackApplicationTests.java
  src/test/java/com/ark/inflearnback/auditing/AuditingTest.java
  src/test/java/com/ark/inflearnback/domain/lecture/LectureTest.java
  src/test/java/com/ark/inflearnback/user/UserTest.java
Labels: enhancement

#29 초기 설정 누락된 사항 수정보완
  src/main/java/com/ark/inflearnback/config/handler/GlobalRestExceptionHandler.java
  src/main/java/com/ark/inflearnback/config/model/HttpResponse.java
Labels: hotfix

#34 ⚙ 협업툴 설정까지 마무리
  .github/pr-badge.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/gradle.yml
  .github/workflows/jira-link.yml
  README.md
  build.gradle
  src/main/java/com/ark/inflearnback/config/logger/http/HttpLogQueryRepository.java
  src/main/java/com/ark/inflearnback/config/logger/http/HttpLogQueryRepositoryImpl.java
  src/main/java/com/ark/inflearnback/config/logger/http/HttpLogRepository.java
  src/main/java/com/ark/inflearnback/domain/AbstractEntity.java
  src/test/java/com/ark/inflearnback/ApplicationTest.java
  src/test/resources/spring.properties
Labels: feature

#36 ARK-2
  .github/workflows/gradle-cd.yml
  .github/workflows/gradle-ci.yml
  appspec.yml
  build.gradle
  src/main/resources/logback-spring.xml
Labels: feature

#37 ⚙ CD 테스트
  .github/workflows/gradle-cd.yml
  .github/workflows/gradle-ci.yml
  appspec.yml
  build.gradle
  src/main/resources/logback-spring.xml
Labels: feature

#76 ARK-3 스프링 시큐리티 Oauth2 구축
  .gitignore
  build.gradle
  src/main/generated/com/ark/inflearnback/config/logger/http/QHttpLog 2.java
  src/main/generated/com/ark/inflearnback/config/logger/http/QHttpLog.java
  src/main/generated/com/ark/inflearnback/domain/QAbstractEntity.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QMember.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QResource 2.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QResource.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QRole.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QRoleHierarchies.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QRoleResource.java
  src/main/java/com/ark/inflearnback/config/jasypt/JasyptConfig.java
  src/main/java/com/ark/inflearnback/config/jasypt/JasyptProperties.java
  src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
  src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
  src/main/java/com/ark/inflearnback/domain/security/dto/SessionMember.java
  src/main/java/com/ark/inflearnback/domain/security/exception/Oauth2UserNotVerifiedException.java
  src/main/java/com/ark/inflearnback/domain/security/model/Member.java
  src/main/java/com/ark/inflearnback/domain/security/service/CustomOauth2UserService.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/test/java/com/ark/inflearnback/config/jasypt/JasyptConfigTest.java
  src/test/java/com/ark/inflearnback/config/security/Oauth2Test.java
  src/test/resources/application-test.properties
Labels: feature

#96 spring security denied access to h2-console
  src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: bug

#97 Failed to bind properties under 'spring.security.oauth2.client.registration.google.client-id' to java.lang.String:
  src/main/java/com/ark/inflearnback/config/jasypt/JasyptConfig.java
  src/main/java/com/ark/inflearnback/config/jasypt/JasyptProperties.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/test/java/com/ark/inflearnback/config/jasypt/JasyptConfigTest.java
  src/test/java/com/ark/inflearnback/config/security/Oauth2Test.java
  src/test/resources/application-test.properties
Labels: bug

#99 The OAuth client was not found
  src/main/resources/application.yml
Labels: bug

#102 hotfix: api documentation
  src/main/java/com/ark/inflearnback/config/interceptor/InterceptorConfig.java
  src/main/resources/static/api/index.html
Labels: hotfix

#103 hotfix: api documentation, jasypt
  src/main/java/com/ark/inflearnback/config/interceptor/InterceptorConfig.java
  src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: hotfix

#104 Bugfix/api docs
  .github/workflows/gradle-cd.yml
  .github/workflows/gradle-ci.yml
  src/main/resources/application.yml
  src/main/resources/banner.txt
  src/test/resources/application-test.properties
  src/test/resources/application-test.yml
Labels: bug

#105 Update gradle-cd.yml
  .github/workflows/gradle-cd.yml
  src/main/generated/com/ark/inflearnback/config/logger/http/QHttpLog 2.java
  src/main/generated/com/ark/inflearnback/config/logger/http/QHttpLog.java
  src/main/generated/com/ark/inflearnback/domain/QAbstractEntity.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QMember.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QResource 2.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QResource.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QRole.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QRoleHierarchies.java
  src/main/generated/com/ark/inflearnback/domain/security/model/QRoleResource.java
  src/main/java/com/ark/inflearnback/config/jasypt/JasyptConfig.java
  src/main/java/com/ark/inflearnback/config/jasypt/JasyptProperties.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/test/java/com/ark/inflearnback/config/jasypt/JasyptConfigTest.java
  src/test/java/com/ark/inflearnback/config/security/Oauth2Test.java
  src/test/resources/application-test.properties
Labels: bug

#107 Update develop
  .github/workflows/codeql-analysis.yml
  src/main/java/com/ark/inflearnback/config/jasypt/JasyptConfig.java
  src/main/java/com/ark/inflearnback/config/jasypt/JasyptProperties.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/test/java/com/ark/inflearnback/config/jasypt/JasyptConfigTest.java
  src/test/java/com/ark/inflearnback/config/security/Oauth2Test.java
  src/test/resources/application-test.properties
Labels: bug
