Repository TEAM-ARK/sprout-backend, pull requests merged in 2021-09, with the labels that each got.

#114 Update README.md
  README.md
Labels: documentation

#120 ARK-12 프로젝트 리팩토링, 일부 버그 수정
  src/main/java/com/ark/inflearnback/config/interceptor/InterceptorConfig.java
  src/main/java/com/ark/inflearnback/config/web/CorsConfig.java
  src/main/java/com/ark/inflearnback/config/web/WebConfig.java
  src/main/java/com/ark/inflearnback/domain/AbstractEntity.java
  src/main/java/com/ark/inflearnback/domain/member/service/MemberManagementService.java
  src/main/java/com/ark/inflearnback/domain/security/filter/PermitAllFilter.java
  src/main/java/com/ark/inflearnback/domain/security/model/Member.java
  src/main/java/com/ark/inflearnback/domain/security/token/RestAuthenticationToken.java
Labels: bug, documentation, feature

#129 Ark 10 : 무중단 배포
  deploy.sh
Labels: feature

#119 ARK - 9 Oauth 2 로그인 연동 기능
  gradlew
  src/main/java/com/ark/inflearnback/config/model/HttpResponse.java
  src/main/java/com/ark/inflearnback/domain/member/service/MemberManagementService.java
  src/main/java/com/ark/inflearnback/domain/security/SecurityConfig.java
  src/main/java/com/ark/inflearnback/domain/security/SecurityDatabaseInitializer.java
  src/main/java/com/ark/inflearnback/domain/security/dto/OAuthAttributes.java
  src/main/java/com/ark/inflearnback/domain/security/exception/Oauth2UserNotVerifiedException.java
  src/main/java/com/ark/inflearnback/domain/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/ark/inflearnback/domain/security/handler/Oauth2AuthenticationFailureHandler.java
  src/main/java/com/ark/inflearnback/domain/security/handler/Oauth2AuthenticationSuccessHandler.java
  src/main/java/com/ark/inflearnback/domain/security/handler/RestAuthenticationFailureHandler.java
  src/main/java/com/ark/inflearnback/domain/security/handler/RestAuthenticationSuccessHandler.java
  src/main/java/com/ark/inflearnback/domain/security/model/Member.java
  src/main/java/com/ark/inflearnback/domain/security/provider/UsernamePasswordAuthenticationProvider.java
  src/main/java/com/ark/inflearnback/domain/security/repository/MemberRepository.java
  src/main/java/com/ark/inflearnback/domain/security/service/CustomOauth2UserService.java
  src/main/java/com/ark/inflearnback/domain/security/service/RestUserDetailsService.java
  src/main/java/com/ark/inflearnback/domain/security/type/RoleType.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/ark/inflearnback/domain/member/controller/RestLoginTest.java
  src/test/java/com/ark/inflearnback/domain/security/repository/MemberRepositoryTest.java
  src/test/resources/application-test.yml
Labels: feature

#137 ARK-17 CORS Preflight
  src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
  src/main/java/com/ark/inflearnback/configuration/web/WebConfiguration.java
Labels: bug

#138 hotfix: v0.0.2
  src/main/java/com/ark/inflearnback/configuration/filter/ServletWrappingFilter.java
  src/main/java/com/ark/inflearnback/configuration/handler/GlobalRestControllerExceptionHandler.java
  src/main/java/com/ark/inflearnback/configuration/interceptor/HttpLogInterceptor.java
  src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
  src/main/java/com/ark/inflearnback/configuration/security/model/entity/Member.java
  src/main/java/com/ark/inflearnback/configuration/security/model/entity/RoleHierarchies.java
  src/main/java/com/ark/inflearnback/configuration/security/provider/UsernamePasswordAuthenticationProvider.java
  src/main/java/com/ark/inflearnback/configuration/web/WebConfiguration.java
Labels: feature

#139 Hotfix - ObjectMapper 생성부 제거, CORS Credentials 허용
  src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/Oauth2AuthenticationSuccessHandler.java
Labels: hotfix

#140 hotfix: v0.0.3
  src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/Oauth2AuthenticationSuccessHandler.java
Labels: hotfix

#141 hotfix: Update allow CORS patterns
  src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
Labels: bug, hotfix

#142 hotfix: v0.0.4
  src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
Labels: bug, hotfix

#143 refactor: 2021-09-22
  src/main/java/com/ark/inflearnback/configuration/http/model/entity/HttpLog.java
  src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
  src/main/java/com/ark/inflearnback/configuration/security/factory/UrlResourcesMapFactoryBean.java
  src/main/java/com/ark/inflearnback/configuration/security/filter/PermitAllFilter.java
  src/main/java/com/ark/inflearnback/configuration/security/filter/UrlFilterInvocationSecurityMetadataSource.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/Oauth2AuthenticationSuccessHandler.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/UsernamePasswordAuthenticationFailureHandler.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/UsernamePasswordAuthenticationSuccessHandler.java
  src/main/java/com/ark/inflearnback/configuration/security/model/entity/Member.java
  src/main/java/com/ark/inflearnback/configuration/security/provider/UsernamePasswordAuthenticationProvider.java
  src/main/java/com/ark/inflearnback/domain/member/controller/MemberApiController.java
  src/main/java/com/ark/inflearnback/domain/member/service/MemberService.java
Labels: feature

#144 ARK-13 Session Timeout
  src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
  src/main/resources/application.yml
Labels: feature

#145 ARK-19 시스템 관리자 환경 구축
  README.md
  build.gradle
  src/main/java/com/ark/inflearnback/configuration/http/model/entity/HttpLog.java
  src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
  src/main/java/com/ark/inflearnback/configuration/security/filter/PermitAllFilter.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/Oauth2AuthenticationSuccessHandler.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/UsernamePasswordAuthenticationFailureHandler.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/UsernamePasswordAuthenticationSuccessHandler.java
  src/main/java/com/ark/inflearnback/configuration/security/model/entity/Resource.java
  src/main/java/com/ark/inflearnback/domain/member/controller/MemberApiController.java
  src/main/resources/static/docs/api/open-api-3.0.1.json
  src/test/java/com/ark/inflearnback/domain/member/controller/MemberApiControllerTest.java
Labels: bug, feature, invalid

#146 v0.0.5
  README.md
  build.gradle
  src/main/java/com/ark/inflearnback/configuration/http/model/entity/HttpLog.java
  src/main/java/com/ark/inflearnback/configuration/security/SecurityConfiguration.java
  src/main/java/com/ark/inflearnback/configuration/security/factory/UrlResourcesMapFactoryBean.java
  src/main/java/com/ark/inflearnback/configuration/security/filter/PermitAllFilter.java
  src/main/java/com/ark/inflearnback/configuration/security/filter/UrlFilterInvocationSecurityMetadataSource.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/Oauth2AuthenticationSuccessHandler.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/UsernamePasswordAuthenticationFailureHandler.java
  src/main/java/com/ark/inflearnback/configuration/security/handler/UsernamePasswordAuthenticationSuccessHandler.java
  src/main/java/com/ark/inflearnback/configuration/security/model/entity/Member.java
  src/main/java/com/ark/inflearnback/configuration/security/model/entity/Resource.java
  src/main/java/com/ark/inflearnback/configuration/security/provider/UsernamePasswordAuthenticationProvider.java
  src/main/java/com/ark/inflearnback/domain/member/controller/MemberApiController.java
  src/main/java/com/ark/inflearnback/domain/member/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/static/docs/api/open-api-3.0.1.json
  src/test/java/com/ark/inflearnback/domain/member/controller/MemberApiControllerTest.java
Labels: feature

#150 bugfix: jasypt password로 인해 테스트코드가 간헐적으로 실패하는 현상 해결
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/static/docs/api/open-api-3.0.1.json
  src/test/java/com/ark/inflearnback/domain/member/controller/MemberApiControllerTest.java
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: bug, invalid, trouble-shooting
